<?xml version="1.0"?>
<!DOCTYPE SimpleConfiguration [
<!ELEMENT SimpleConfiguration (ConfigurationName*,  Item*, List*)>
<!ELEMENT ConfigurationName (#PCDATA)>
<!ELEMENT Item (#PCDATA)>
<!ELEMENT List (ListItem*)>
<!ELEMENT ListItem (#PCDATA)>
<!ATTLIST Item name CDATA "none">
<!ATTLIST List name CDATA "none">
<!ATTLIST ListItem name CDATA "none">
]>

<SimpleConfiguration>
	<List name="colorblind">
		<ListItem name="">0.0,0.447058823529,0.698039215686</ListItem>
		<ListItem name="">0.0,0.619607843137,0.450980392157</ListItem>
		<ListItem name="">0.835294117647,0.36862745098,0.0</ListItem>
		<ListItem name="">0.8,0.474509803922,0.654901960784</ListItem>
		<ListItem name="">0.941176470588,0.894117647059,0.258823529412</ListItem>
		<ListItem name="">0.337254901961,0.705882352941,0.913725490196</ListItem>
	</List>
	<List name="coolwarm">
		<ListItem name="">0.248091217804,0.326013023318,0.777668651353</ListItem>
		<ListItem name="">0.266381468353,0.353304408424,0.801637319498</ListItem>
		<ListItem name="">0.285272777529,0.380129422635,0.823468551247</ListItem>
		<ListItem name="">0.304174287004,0.406944882839,0.845262726698</ListItem>
		<ListItem name="">0.323718415255,0.433158440549,0.864722355373</ListItem>
		<ListItem name="">0.348323341412,0.46571114651,0.888346162941</ListItem>
		<ListItem name="">0.368506613318,0.491141193631,0.905243128212</ListItem>
		<ListItem name="">0.388851871953,0.516298435576,0.921373483082</ListItem>
		<ListItem name="">0.409611096675,0.540758508737,0.935544722486</ListItem>
		<ListItem name="">0.430506888251,0.564882741459,0.94888941918</ListItem>
		<ListItem name="">0.457046478525,0.594005549929,0.96302922969</ListItem>
		<ListItem name="">0.478462251294,0.616563643608,0.972720895431</ListItem>
		<ListItem name="">0.500030564518,0.638508467576,0.981070124106</ListItem>
		<ListItem name="">0.521696280831,0.659598606353,0.987736023247</ListItem>
		<ListItem name="">0.543440193992,0.680002589412,0.993050516988</ListItem>
		<ListItem name="">0.570616436878,0.704109161804,0.997194831059</ListItem>
		<ListItem name="">0.592355859498,0.722792029255,0.999433874824</ListItem>
		<ListItem name="">0.613932652765,0.739922982294,0.999142372059</ListItem>
		<ListItem name="">0.635473822459,0.756713992176,0.998296559102</ListItem>
		<ListItem name="">0.656682867549,0.771806476765,0.994913837753</ListItem>
		<ListItem name="">0.683055681561,0.79004262689,0.989768428184</ListItem>
		<ListItem name="">0.703586888086,0.802585636522,0.982847132875</ListItem>
		<ListItem name="">0.724041371882,0.814910392647,0.975650970647</ListItem>
		<ListItem name="">0.743754202627,0.825125364882,0.965797761549</ListItem>
		<ListItem name="">0.763362780102,0.83509222182,0.955657676557</ListItem>
		<ListItem name="">0.786720701357,0.844807210369,0.939810384949</ListItem>
		<ListItem name="">0.804964758824,0.851666160557,0.926165074431</ListItem>
		<ListItem name="">0.822420404941,0.856897516541,0.910795130588</ListItem>
		<ListItem name="">0.839351442773,0.861166825655,0.894493763416</ListItem>
		<ListItem name="">0.855378368451,0.863778139098,0.876587177314</ListItem>
		<ListItem name="">0.875557387431,0.860242158863,0.851430066098</ListItem>
		<ListItem name="">0.891816892122,0.851973277043,0.829085274255</ListItem>
		<ListItem name="">0.906154134035,0.842091065176,0.806150593082</ListItem>
		<ListItem name="">0.919375988906,0.831272723529,0.782873630447</ListItem>
		<ListItem name="">0.930668596333,0.818876999655,0.759146390698</ListItem>
		<ListItem name="">0.943431529667,0.802276253616,0.729171597914</ListItem>
		<ListItem name="">0.95095561298,0.786875033333,0.704760682804</ListItem>
		<ListItem name="">0.958176031741,0.7712340904,0.680301036812</ListItem>
		<ListItem name="">0.962708278329,0.753557346557,0.655601211227</ListItem>
		<ListItem name="">0.966962438141,0.73567000262,0.630876539478</ListItem>
		<ListItem name="">0.968862500365,0.710838483812,0.599900504431</ListItem>
		<ListItem name="">0.969682979667,0.690483930737,0.575138361365</ListItem>
		<ListItem name="">0.968105337,0.668475196118,0.550486220941</ListItem>
		<ListItem name="">0.966016719839,0.646129741588,0.525890348259</ListItem>
		<ListItem name="">0.961595393031,0.622247087471,0.501551350047</ListItem>
		<ListItem name="">0.954853405612,0.591622345008,0.47133746349</ListItem>
		<ListItem name="">0.947654184153,0.565976434169,0.447478148039</ListItem>
		<ListItem name="">0.939253771518,0.539581488565,0.423900204929</ListItem>
		<ListItem name="">0.929357138294,0.512253534745,0.400672743157</ListItem>
		<ListItem name="">0.918281672584,0.48417347218,0.377793925071</ListItem>
		<ListItem name="">0.902658929369,0.447938747161,0.349721373541</ListItem>
		<ListItem name="">0.888390490741,0.41770291749,0.327897911004</ListItem>
		<ListItem name="">0.873402282553,0.386959639059,0.306332463976</ListItem>
		<ListItem name="">0.856715867651,0.354703855012,0.285487297937</ListItem>
		<ListItem name="">0.839364937078,0.321856220941,0.26492398098</ListItem>
		<ListItem name="">0.815508386608,0.277780987176,0.240293565667</ListItem>
		<ListItem name="">0.795937539486,0.241845285341,0.220829749133</ListItem>
		<ListItem name="">0.774336850153,0.199759268047,0.202534554435</ListItem>
		<ListItem name="">0.752703941102,0.157575626698,0.18425790929</ListItem>
		<ListItem name="">0.729195931835,0.0866789368471,0.167240403404</ListItem>
	</List>
	<List name="cubehelix">
		<ListItem name="">0.863516743655,0.826404481351,0.948607279022</ListItem>
		<ListItem name="">0.634710725849,0.798506666986,0.830990445188</ListItem>
		<ListItem name="">0.538161282547,0.73040677833,0.532652840625</ListItem>
		<ListItem name="">0.636187069148,0.537792592871,0.371507608941</ListItem>
		<ListItem name="">0.625432640165,0.358914850689,0.469009414764</ListItem>
		<ListItem name="">0.367506389814,0.306837461802,0.524852002616</ListItem>
		<ListItem name="">0.130012306056,0.29836554437,0.326735895975</ListItem>
		<ListItem name="">0.0876794093286,0.192864227936,0.0811434717803</ListItem>
	</List>
	<List name="cubehelixhuge">
		<ListItem name="">0.681822712016,0.764832059057,0.883122320543</ListItem>
		<ListItem name="">0.615599805334,0.791522688989,0.813618680503</ListItem>
		<ListItem name="">0.590348401294,0.802801153476,0.715040058113</ListItem>
		<ListItem name="">0.600517202103,0.796944047851,0.647420929852</ListItem>
		<ListItem name="">0.651099804148,0.766354142422,0.566589839871</ListItem>
		<ListItem name="">0.725298513445,0.715040997733,0.532503604181</ListItem>
		<ListItem name="">0.773531915847,0.675539528793,0.541528869836</ListItem>
		<ListItem name="">0.82200885997,0.620437474923,0.59791550925</ListItem>
		<ListItem name="">0.828653161042,0.59321541,0.654503211646</ListItem>
		<ListItem name="">0.793176570853,0.574683341192,0.743705310726</ListItem>
		<ListItem name="">0.710292741148,0.58510920986,0.806879424511</ListItem>
		<ListItem name="">0.639722818077,0.605152110586,0.820538289066</ListItem>
		<ListItem name="">0.534626009404,0.644551692298,0.788888028674</ListItem>
		<ListItem name="">0.479300919502,0.669376144935,0.735323327707</ListItem>
		<ListItem name="">0.437270935304,0.691768880594,0.622891317481</ListItem>
		<ListItem name="">0.45334341442,0.685988606852,0.503108341682</ListItem>
		<ListItem name="">0.4929435501,0.664726496124,0.437849080882</ListItem>
		<ListItem name="">0.578086104745,0.611474055434,0.384317666074</ListItem>
		<ListItem name="">0.63754332313,0.567840318071,0.384896569449</ListItem>
		<ListItem name="">0.704957193852,0.503796304856,0.437598625827</ListItem>
		<ListItem name="">0.72251693398,0.457355632496,0.53184833167</ListItem>
		<ListItem name="">0.700437763062,0.442549535778,0.600177827088</ListItem>
		<ListItem name="">0.62174565491,0.447406156794,0.681791539764</ListItem>
		<ListItem name="">0.548852619019,0.466264973271,0.708137214946</ListItem>
		<ListItem name="">0.433631635445,0.507857599547,0.692335640879</ListItem>
		<ListItem name="">0.342914707139,0.548836333608,0.612997388787</ListItem>
		<ListItem name="">0.310072529194,0.566683795873,0.535537773753</ListItem>
		<ListItem name="">0.311730351749,0.569472093825,0.409108616747</ListItem>
		<ListItem name="">0.344669616246,0.553202362114,0.335237948166</ListItem>
		<ListItem name="">0.426066417599,0.504946284153,0.265123418892</ListItem>
		<ListItem name="">0.516448037234,0.440029482036,0.259867368807</ListItem>
		<ListItem name="">0.564185602885,0.396484328718,0.291933897878</ListItem>
		<ListItem name="">0.596089408102,0.344334701527,0.377684273629</ListItem>
		<ListItem name="">0.584629364675,0.324301483914,0.44508898549</ListItem>
		<ListItem name="">0.520383143687,0.320677405133,0.532792389171</ListItem>
		<ListItem name="">0.41780089687,0.345001821458,0.575142391513</ListItem>
		<ListItem name="">0.343519426192,0.370687796657,0.568656106414</ListItem>
		<ListItem name="">0.248586535097,0.410450913849,0.507336125124</ListItem>
		<ListItem name="">0.20850380744,0.430073072202,0.44010462854</ListItem>
		<ListItem name="">0.194580808916,0.439025962758,0.32310389058</ListItem>
		<ListItem name="">0.233919756851,0.418441866919,0.21926954533</ListItem>
		<ListItem name="">0.280946142692,0.389840411599,0.173122633315</ListItem>
		<ListItem name="">0.361045004716,0.333118695567,0.151954814005</ListItem>
		<ListItem name="">0.406950056426,0.293049144377,0.170377145547</ListItem>
		<ListItem name="">0.444674753078,0.24183393946,0.235240396835</ListItem>
		<ListItem name="">0.43257047289,0.212417307782,0.319080864845</ListItem>
		<ListItem name="">0.397250956041,0.207769836488,0.369032987057</ListItem>
		<ListItem name="">0.315470401832,0.221094192619,0.413651638017</ListItem>
		<ListItem name="">0.252932859362,0.239235240398,0.415604867598</ListItem>
		<ListItem name="">0.16826877255,0.269886262001,0.375153244186</ListItem>
		<ListItem name="">0.115484091571,0.291692505145,0.295198041878</ListItem>
		<ListItem name="">0.104491213106,0.295727071282,0.23223707598</ListItem>
		<ListItem name="">0.12335834543,0.282476417033,0.144900938457</ListItem>
		<ListItem name="">0.153642897188,0.261707059665,0.102404907527</ListItem>
		<ListItem name="">0.20951104,0.21870528,0.07373184</ListItem>
		<ListItem name="">0.256522795994,0.172177513104,0.0881248319413</ListItem>
		<ListItem name="">0.273136513231,0.145250232223,0.115942032886</ListItem>
		<ListItem name="">0.26854642322,0.117694313206,0.16930896497</ListItem>
		<ListItem name="">0.24626886755,0.109579270767,0.202290920796</ListItem>
		<ListItem name="">0.19219588654,0.111448746849,0.232783460742</ListItem>
	</List>
	<List name="cubehelixlarge">
		<ListItem name="">0.828576145091,0.880007983816,0.756388672437</ListItem>
		<ListItem name="">0.847152088875,0.838311634765,0.71546762536</ListItem>
		<ListItem name="">0.871063725733,0.789500632539,0.698155289156</ListItem>
		<ListItem name="">0.888614989883,0.739032102717,0.707079889764</ListItem>
		<ListItem name="">0.886002992114,0.686799473836,0.744806599054</ListItem>
		<ListItem name="">0.855252140424,0.654436377123,0.788353016228</ListItem>
		<ListItem name="">0.796502721171,0.637230020741,0.826963619638</ListItem>
		<ListItem name="">0.715066186236,0.635212230315,0.845981896817</ListItem>
		<ListItem name="">0.621996923,0.644837637985,0.834275625083</ListItem>
		<ListItem name="">0.518038426735,0.662058514307,0.77587699036</ListItem>
		<ListItem name="">0.449364230442,0.672792308512,0.691693551652</ListItem>
		<ListItem name="">0.41086883957,0.671845337758,0.587855834102</ListItem>
		<ListItem name="">0.406807701443,0.654020936393,0.480631232687</ListItem>
		<ListItem name="">0.434021965617,0.617670539768,0.387477165997</ListItem>
		<ListItem name="">0.482504554017,0.565132893356,0.32314147344</ListItem>
		<ListItem name="">0.546206598608,0.491333081866,0.295690493047</ListItem>
		<ListItem name="">0.588541791356,0.426705405663,0.312967362076</ListItem>
		<ListItem name="">0.605267221639,0.369726710261,0.359062605236</ListItem>
		<ListItem name="">0.588597547892,0.327105211084,0.419228383122</ListItem>
		<ListItem name="">0.538003849597,0.302364603897,0.476007277143</ListItem>
		<ListItem name="">0.46019222901,0.295127904874,0.513131892321</ListItem>
		<ListItem name="">0.351571522125,0.303179651946,0.516628566259</ListItem>
		<ListItem name="">0.260283394493,0.316308003584,0.481276014464</ListItem>
		<ListItem name="">0.185256595337,0.326896185005,0.415198913756</ListItem>
		<ListItem name="">0.135868461937,0.328100588438,0.329529486816</ListItem>
		<ListItem name="">0.11522246791,0.31561062778,0.238924246113</ListItem>
		<ListItem name="">0.122429376406,0.282688756818,0.146295576039</ListItem>
		<ListItem name="">0.144869781411,0.241835657973,0.0903121519009</ListItem>
		<ListItem name="">0.169718009954,0.194866642501,0.0605656645755</ListItem>
		<ListItem name="">0.185673933946,0.148017523217,0.054427888123</ListItem>
	</List>
	<List name="dark">
		<ListItem name="">0.0,0.109803921569,0.498039215686</ListItem>
		<ListItem name="">0.00392156862745,0.458823529412,0.0901960784314</ListItem>
		<ListItem name="">0.549019607843,0.0352941176471,0.0</ListItem>
		<ListItem name="">0.462745098039,0.0,0.63137254902</ListItem>
		<ListItem name="">0.721568627451,0.525490196078,0.043137254902</ListItem>
		<ListItem name="">0.0,0.388235294118,0.454901960784</ListItem>
	</List>
	<List name="deep">
		<ListItem name="">0.298039215686,0.447058823529,0.690196078431</ListItem>
		<ListItem name="">0.333333333333,0.658823529412,0.407843137255</ListItem>
		<ListItem name="">0.76862745098,0.305882352941,0.321568627451</ListItem>
		<ListItem name="">0.505882352941,0.447058823529,0.698039215686</ListItem>
		<ListItem name="">0.8,0.725490196078,0.454901960784</ListItem>
		<ListItem name="">0.392156862745,0.709803921569,0.803921568627</ListItem>
	</List>
	<List name="default">
		<ListItem name="">0.298039215686,0.447058823529,0.690196078431</ListItem>
		<ListItem name="">0.333333333333,0.658823529412,0.407843137255</ListItem>
		<ListItem name="">0.76862745098,0.305882352941,0.321568627451</ListItem>
		<ListItem name="">0.505882352941,0.447058823529,0.698039215686</ListItem>
		<ListItem name="">0.8,0.725490196078,0.454901960784</ListItem>
		<ListItem name="">0.392156862745,0.709803921569,0.803921568627</ListItem>
	</List>
	<List name="hls">
		<ListItem name="">0.86,0.3712,0.34</ListItem>
		<ListItem name="">0.86,0.4232,0.34</ListItem>
		<ListItem name="">0.86,0.4752,0.34</ListItem>
		<ListItem name="">0.86,0.5272,0.34</ListItem>
		<ListItem name="">0.86,0.5792,0.34</ListItem>
		<ListItem name="">0.86,0.6312,0.34</ListItem>
		<ListItem name="">0.86,0.6832,0.34</ListItem>
		<ListItem name="">0.86,0.7352,0.34</ListItem>
		<ListItem name="">0.86,0.7872,0.34</ListItem>
		<ListItem name="">0.86,0.8392,0.34</ListItem>
		<ListItem name="">0.8288,0.86,0.34</ListItem>
		<ListItem name="">0.7768,0.86,0.34</ListItem>
		<ListItem name="">0.7248,0.86,0.34</ListItem>
		<ListItem name="">0.6728,0.86,0.34</ListItem>
		<ListItem name="">0.6208,0.86,0.34</ListItem>
		<ListItem name="">0.5688,0.86,0.34</ListItem>
		<ListItem name="">0.5168,0.86,0.34</ListItem>
		<ListItem name="">0.4648,0.86,0.34</ListItem>
		<ListItem name="">0.4128,0.86,0.34</ListItem>
		<ListItem name="">0.3608,0.86,0.34</ListItem>
		<ListItem name="">0.34,0.86,0.3712</ListItem>
		<ListItem name="">0.34,0.86,0.4232</ListItem>
		<ListItem name="">0.34,0.86,0.4752</ListItem>
		<ListItem name="">0.34,0.86,0.5272</ListItem>
		<ListItem name="">0.34,0.86,0.5792</ListItem>
		<ListItem name="">0.34,0.86,0.6312</ListItem>
		<ListItem name="">0.34,0.86,0.6832</ListItem>
		<ListItem name="">0.34,0.86,0.7352</ListItem>
		<ListItem name="">0.34,0.86,0.7872</ListItem>
		<ListItem name="">0.34,0.86,0.8392</ListItem>
		<ListItem name="">0.34,0.8288,0.86</ListItem>
		<ListItem name="">0.34,0.7768,0.86</ListItem>
		<ListItem name="">0.34,0.7248,0.86</ListItem>
		<ListItem name="">0.34,0.6728,0.86</ListItem>
		<ListItem name="">0.34,0.6208,0.86</ListItem>
		<ListItem name="">0.34,0.5688,0.86</ListItem>
		<ListItem name="">0.34,0.5168,0.86</ListItem>
		<ListItem name="">0.34,0.4648,0.86</ListItem>
		<ListItem name="">0.34,0.4128,0.86</ListItem>
		<ListItem name="">0.34,0.3608,0.86</ListItem>
		<ListItem name="">0.3712,0.34,0.86</ListItem>
		<ListItem name="">0.4232,0.34,0.86</ListItem>
		<ListItem name="">0.4752,0.34,0.86</ListItem>
		<ListItem name="">0.5272,0.34,0.86</ListItem>
		<ListItem name="">0.5792,0.34,0.86</ListItem>
		<ListItem name="">0.6312,0.34,0.86</ListItem>
		<ListItem name="">0.6832,0.34,0.86</ListItem>
		<ListItem name="">0.7352,0.34,0.86</ListItem>
		<ListItem name="">0.7872,0.34,0.86</ListItem>
		<ListItem name="">0.8392,0.34,0.86</ListItem>
		<ListItem name="">0.86,0.34,0.8288</ListItem>
		<ListItem name="">0.86,0.34,0.7768</ListItem>
		<ListItem name="">0.86,0.34,0.7248</ListItem>
		<ListItem name="">0.86,0.34,0.6728</ListItem>
		<ListItem name="">0.86,0.34,0.6208</ListItem>
		<ListItem name="">0.86,0.34,0.5688</ListItem>
		<ListItem name="">0.86,0.34,0.5168</ListItem>
		<ListItem name="">0.86,0.34,0.4648</ListItem>
		<ListItem name="">0.86,0.34,0.4128</ListItem>
		<ListItem name="">0.86,0.34,0.3608</ListItem>
	</List>
	<List name="husl">
		<ListItem name="">0.967797559292,0.441274560092,0.535810315506</ListItem>
		<ListItem name="">0.968630067277,0.447422248543,0.478571824893</ListItem>
		<ListItem name="">0.969497975429,0.453728438705,0.407834662149</ListItem>
		<ListItem name="">0.970424156998,0.4603475375,0.309935986455</ListItem>
		<ListItem name="">0.954290008036,0.477950517589,0.196391762212</ListItem>
		<ListItem name="">0.903599057665,0.511987276336,0.195883500602</ListItem>
		<ListItem name="">0.861609064729,0.536495730113,0.195488990315</ListItem>
		<ListItem name="">0.825371586685,0.555421134033,0.195167604323</ListItem>
		<ListItem name="">0.793004624437,0.570810052245,0.194895319844</ListItem>
		<ListItem name="">0.763210562455,0.58384606164,0.19465686802</ListItem>
		<ListItem name="">0.735022898563,0.595271990475,0.194441913385</ListItem>
		<ListItem name="">0.707658387733,0.605587216409,0.194243026368</ListItem>
		<ListItem name="">0.680418912779,0.615149751468,0.194054521114</ListItem>
		<ListItem name="">0.652613622294,0.624233849652,0.193871733955</ListItem>
		<ListItem name="">0.623480965909,0.633065491877,0.193690529337</ListItem>
		<ListItem name="">0.592089152964,0.641846701638,0.193506913499</ListItem>
		<ListItem name="">0.557180387024,0.650774773993,0.193316675883</ListItem>
		<ListItem name="">0.516884287594,0.66006051967,0.193114987936</ListItem>
		<ListItem name="">0.468102568234,0.669949253579,0.19289587399</ListItem>
		<ListItem name="">0.404901898044,0.680749261752,0.192651420958</ListItem>
		<ListItem name="">0.31268900195,0.69287546103,0.192370483033</ListItem>
		<ListItem name="">0.19316929745,0.701841807824,0.243213884074</ListItem>
		<ListItem name="">0.196459989007,0.697430911984,0.361468008832</ListItem>
		<ListItem name="">0.199077716962,0.693837187623,0.43063109588</ListItem>
		<ListItem name="">0.201253172212,0.690792081538,0.479667611893</ListItem>
		<ListItem name="">0.203127571979,0.68812492498,0.517761816745</ListItem>
		<ListItem name="">0.20479342237,0.685720190046,0.549153960623</ListItem>
		<ListItem name="">0.206315164052,0.683494816773,0.576181743765</ListItem>
		<ListItem name="">0.207740523479,0.681385219137,0.600290039897</ListItem>
		<ListItem name="">0.209107259155,0.679339216943,0.622455397476</ListItem>
		<ListItem name="">0.210447538322,0.677310508046,0.643394116847</ListItem>
		<ListItem name="">0.211791120995,0.675254341192,0.663677703036</ListItem>
		<ListItem name="">0.213168062824,0.673123492621,0.683805674152</ListItem>
		<ListItem name="">0.214611475689,0.670863755628,0.704259489063</ListItem>
		<ListItem name="">0.216160905002,0.668407980944,0.72555157741</ListItem>
		<ListItem name="">0.217867106624,0.665667160132,0.748280938507</ListItem>
		<ListItem name="">0.219799566083,0.662515787685,0.773209315932</ListItem>
		<ListItem name="">0.222059370116,0.658765873537,0.80138116621</ListItem>
		<ListItem name="">0.224803014386,0.654117034131,0.834333548269</ListItem>
		<ListItem name="">0.228290307856,0.648051533438,0.874499750737</ListItem>
		<ListItem name="">0.232991209247,0.639586552066,0.926070609398</ListItem>
		<ListItem name="">0.320064947704,0.624701533676,0.958644380918</ListItem>
		<ListItem name="">0.433280341176,0.606527340796,0.958546709827</ListItem>
		<ListItem name="">0.51553312732,0.588285323127,0.958452367795</ListItem>
		<ListItem name="">0.583040854192,0.56953192158,0.958359196637</ListItem>
		<ListItem name="">0.642304434922,0.549768005126,0.958265143366</ListItem>
		<ListItem name="">0.696845664145,0.528377745171,0.958168075927</ListItem>
		<ListItem name="">0.748978264321,0.50453426105,0.958065583468</ListItem>
		<ListItem name="">0.800493618642,0.477033635337,0.957954719601</ListItem>
		<ListItem name="">0.853015906871,0.443965400494,0.957831626091</ListItem>
		<ListItem name="">0.908257243677,0.401957907297,0.957690925029</ListItem>
		<ListItem name="">0.95791485335,0.358831186992,0.947411598577</ListItem>
		<ListItem name="">0.959647907831,0.374829131285,0.893004453766</ListItem>
		<ListItem name="">0.96106620601,0.387353455047,0.844876872634</ListItem>
		<ListItem name="">0.96227239351,0.397645196897,0.800827436343</ListItem>
		<ListItem name="">0.963332174206,0.406438256457,0.759253759957</ListItem>
		<ListItem name="">0.964290311982,0.414201465828,0.718868118603</ListItem>
		<ListItem name="">0.965179195161,0.421254980231,0.678511244165</ListItem>
		<ListItem name="">0.96602378607,0.427831879799,0.636998264206</ListItem>
		<ListItem name="">0.966844722695,0.434113663398,0.592945775294</ListItem>
	</List>
	<List name="muted">
		<ListItem name="">0.282352941176,0.470588235294,0.811764705882</ListItem>
		<ListItem name="">0.41568627451,0.8,0.396078431373</ListItem>
		<ListItem name="">0.839215686275,0.372549019608,0.372549019608</ListItem>
		<ListItem name="">0.705882352941,0.486274509804,0.780392156863</ListItem>
		<ListItem name="">0.76862745098,0.678431372549,0.4</ListItem>
		<ListItem name="">0.466666666667,0.745098039216,0.858823529412</ListItem>
	</List>
	<List name="pastel">
		<ListItem name="">0.572549019608,0.776470588235,1.0</ListItem>
		<ListItem name="">0.592156862745,0.941176470588,0.666666666667</ListItem>
		<ListItem name="">1.0,0.623529411765,0.603921568627</ListItem>
		<ListItem name="">0.81568627451,0.733333333333,1.0</ListItem>
		<ListItem name="">1.0,0.996078431373,0.639215686275</ListItem>
		<ListItem name="">0.690196078431,0.878431372549,0.901960784314</ListItem>
	</List>
</SimpleConfiguration>
